source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'slim'

# Test requirements
gem 'rspec', :group => 'test'
gem 'rack-test', :require => 'rack/test', :group => 'test'


ruby '2.2.0'
gem 'thin' # or mongrel


gem 'cucumber'
gem 'capybara'
# gem 'rspec_junit_formatter'
# gem 'rspec'
gem 'simplecov', "0.8.0.pre"
gem 'guard'   
gem 'guard-rspec'
gem 'byebug'


gem 'erubis', '~> 2.7.0'
# Padrino Stable Gem
gem 'padrino', '0.11.2'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.11.2'
# end
